on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  test:
    uses: ./.github/workflows/main.yml
    with:
      app_name: vue-ai-tools